[icons]  
name = "awesome"
[icons.overrides]
cpu = ""
update = ""

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#43565e"
idle_fg = "#abcdef"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = " "
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "time"
interval = 60
format = "%a %R"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "mpd"
buttons = ["play", "prev", "next"]
marquee_speed = 0.4
marquee_interval = 0
max_width = 13

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "custom"
command = "echo  "
on_click = "nautilus --name=quickfile"
interval = 1
